### ISSUE TITLE
error when running on master version

### ISSUE THREAD

**Issue by sibelius** [jhen0409/react-native-debugger#226]
I did:

```
yarn
yarn build
yarn pack-macos
open release/React\ Native\ Debugger-darwin-x64/React\ Native\ Debugger.app
```

got 2 errors:

````
Uncaught Error: Cannot find module 'electron-named-image'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/sibelius/Dev/entria/app/react-native-debugger/release/React Native Debugger-darwin-x64/React Native Debugger.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
```

and this one:

```
Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at EventEmitter.electron.ipcRenderer.on (/Users/sibelius/Dev/entria/app/react-native-debugger/release/React Native Debugger-darwin-x64/React Native Debugger.app/Contents/Resources/electron.asar/renderer/init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
```

**Comment by jhen0409** [comment]
Could you check the `electron-named-image` package is installed successfully in `dist/node_modules`? Or just retry with `yarn postinstall`.

**Comment by sibelius** [comment]
Tks for the help, I’ll try again soon
