### ISSUE TITLE
doesn't start on windows giving an error "Cannot find module 'adbkit'"

### ISSUE THREAD

**Issue by Qvatra** [jhen0409/react-native-debugger#236]
React Native Debugger app version: [v0.7.18]
React Native version: [0.55.2]
Platform: [Android]
Is real device of platform: [No]
Operating System: [Windows]

I have dowloaded prebuilt version v0.7.18 (although after unzipping 'version' file states v1.7.12)
then after executing .exe file RNB showed "loading..." message and the following errors in the console:

module.js:472 Uncaught Error: Cannot find module 'adbkit'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (\\nldw-fs01.gfk.com\homedirs\orzinc\Desktop\rn-debugger\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (file://nldw-fs01.gfk.com/homedirs/orzinc/Desktop/rn-debugger/resources/app.asar/js/bundle.js:9:934462)
    at t (file://nldw-fs01.gfk.com/homedirs/orzinc/Desktop/rn-debugger/resources/app.asar/js/bundle.js:1:115)
    at Object.<anonymous> (file://nldw-fs01.gfk.com/homedirs/orzinc/Desktop/rn-debugger/resources/app.asar/js/bundle.js:1:632359)
    at t (file://nldw-fs01.gfk.com/homedirs/orzinc/Desktop/rn-debugger/resources/app.asar/js/bundle.js:1:115)
    at file://nldw-fs01.gfk.com/homedirs/orzinc/Desktop/rn-debugger/resources/app.asar/js/bundle.js:1:475

(unknown) Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at EventEmitter.electron.ipcRenderer.on (\\nldw-fs01.gfk.com\homedirs\orzinc\Desktop\rn-debugger\resources\electron.asar\renderer\init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)

(unknown) Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at EventEmitter.electron.ipcRenderer.on (\\nldw-fs01.gfk.com\homedirs\orzinc\Desktop\rn-debugger\resources\electron.asar\renderer\init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)

(unknown) Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at EventEmitter.electron.ipcRenderer.on (\\nldw-fs01.gfk.com\homedirs\orzinc\Desktop\rn-debugger\resources\electron.asar\renderer\init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)

(unknown) Uncaught TypeError: window.checkWindowInfo is not a function
    at <anonymous>:1:8
    at EventEmitter.electron.ipcRenderer.on (\\nldw-fs01.gfk.com\homedirs\orzinc\Desktop\rn-debugger\resources\electron.asar\renderer\init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7) 

I have tried install adbkit globally via npm but that didn't help.
Any help would be appreciated. thx.

**Comment by jhen0409** [comment]
Feel free reopen the issue if you still getting the same issue in the latest version of RNDebugger.
