### ISSUE TITLE
Out of memory + Redux devtools not working

### ISSUE THREAD

**Issue by ghasemikasra39** [jhen0409/react-native-debugger#398]
```
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 1.08 GB / 11.63 GB
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.8 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
![image](https://user-images.githubusercontent.com/24314029/64470880-25ee8e00-d15f-11e9-8feb-1fc9e4b118df.png)

![image](https://user-images.githubusercontent.com/24314029/64470851-e627a680-d15e-11e9-988b-7c8e55912c69.png)

**Comment by sambegin** [comment]
We're also getting out of memory error when using the debugger. 
``` 
09-19 10:59:34.661 28117 28950 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 73926864 byte allocation with 25165824 free bytes and 60MB until OOM, max allowed footprint 163026976, growth limit 201326592
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:225)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:256)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okio.Buffer.readString(Buffer.java:713)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okio.Buffer.readUtf8(Buffer.java:684)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-19 10:59:34.661 28117 28950 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

This is not happening when debugging with chrome or without attached react-native-debugger

**Comment by tmaly1980** [comment]
I'm also noticing this issue, I have to restart my computer if I have the dev tool open for more than a few hours. Memory gets exhausted and even closing everything doesn't fix the issue. There's a serious memory leak somewhere.

**Comment by joemewes** [comment]
I have this too.  same scenario.. it is find with browser debugger.  Let me know if there's any test repo/testing I can do to help find/resolve this.

![Screenshot 2020-03-18 13 34 39](https://user-images.githubusercontent.com/1431101/76966707-4a050600-691e-11ea-8713-7967ed9e94c9.png)
