### ISSUE TITLE
Unable to open react-native-debugger on windows 10.

### ISSUE THREAD

**Issue by jesus-hernandezmoreno** [jhen0409/react-native-debugger#409]
React Native Debugger app version: 0.10.1
React Native version: 0.59.9/0.61.1
Platform: Android
Is real device of platform: No
Operating System: Windows 10

Following the guide on Getting Started, I'm unable to open react-native-debugger, the installation only displays a Installing

![Installing](https://user-images.githubusercontent.com/17417706/66257274-6e986780-e75c-11e9-87b7-eb3c4476a64e.PNG)

Then it closes and trying to open it, does nothing, no errors, nothing, the process does not appear on the Task Manager.

Help, this is driving me crazy, already  try restart/shutdown/
shout at the computer/hit the computer/apologize to the computer/ask nicely/upgrade RAM and ... nothing ....

**Comment by KurganskySergey** [comment]
use 0.9.14 for windows and wait for fix. there is already reported issue on this problem

**Comment by 889149885** [comment]
Same Issue happen to me with version 0.10.1.
0.9.14 solved my problem. Thanks.

**Comment by lovetofail** [comment]
I'm too not able to run version 10+. Each time I start version 10 the Windows Event logger shows this error. There is no such error starting version 9.
```
Log Name:      System
Source:        Microsoft-Windows-DistributedCOM
Date:          11/9/2019 7:59:09 PM
Event ID:      10016
Task Category: None
Level:         Error
Keywords:      Classic
User:          DESKTOP-F1TP9Q4\Admin
Computer:      DESKTOP-F1TP9Q4
Description:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user DESKTOP-F1TP9Q4\Admin SID (S-1-5-21-6172739-1773641094-481786281-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-09T17:59:09.730421200Z" />
    <EventRecordID>66724</EventRecordID>
    <Correlation />
    <Execution ProcessID="1080" ThreadID="2492" />
    <Channel>System</Channel>
    <Computer>DESKTOP-F1TP9Q4</Computer>
    <Security UserID="S-1-5-21-6172739-1773641094-481786281-1001" />
  </System>
  <EventData>
    <Data Name="param1">application-specific</Data>
    <Data Name="param2">Local</Data>
    <Data Name="param3">Activation</Data>
    <Data Name="param4">{D63B10C5-BB46-4990-A94F-E40B9D520160}</Data>
    <Data Name="param5">{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}</Data>
    <Data Name="param6">DESKTOP-F1TP9Q4</Data>
    <Data Name="param7">Admin</Data>
    <Data Name="param8">S-1-5-21-6172739-1773641094-481786281-1001</Data>
    <Data Name="param9">LocalHost (Using LRPC)</Data>
    <Data Name="param10">Unavailable</Data>
    <Data Name="param11">Unavailable</Data>
  </EventData>
</Event>
```

**Comment by RikSchefferOberon** [comment]
I'm having the same problem, any news on this?

**Comment by gdoudeng** [comment]
+1

**Comment by jesus-hernandezmoreno** [comment]
I'm still running version 9 .....

**Comment by Amsvartner** [comment]
Same problem here. I can install it (or extract it) but when I try to run it, no GUI appears. I can see the process in the process explorer though, and every time I try to open RND it starts a new one. 

Last version that works is 0.9.14. 
The change log for the next version, 0.10.0:

   - Upgrade Electron version to 6.0.8 #302 @jhen0409
   - Update build-related dependencies #400 @jhen0409

**Comment by alimtunc** [comment]
Almost 2 month and latests versions still not working on win10..

**Comment by KurganskySergey** [comment]
actually react-native is not working on windows either :) There is a problem with regexp in blacklist.js in metro since idk when...

**Comment by maroy1986** [comment]
> actually react-native is not working on windows either :) There is a problem with regexp in blacklist.js in metro since idk when...

This was due to NodeJS 12.8 and up. The latest NodeJS 13 works fine. They changed the way they handle regexp, causing that issue with 12.8, not sure if they rollbacked it on 13 but it works now.

**Comment by ahmadi-akbar** [comment]
i can not run rn-debugger on win 10
rn-debugger ver  v0.11.0-beta-2

when i try to open  it does not run in foreground
but it still running in background

trying to run from PowerShell
~~~~ Reading E:\Install\rn-debugger-windows-x64\resources\app.asar\devtools-helper\manifest.json failed.
Error: Invalid package E:\Install\rn-debugger-windows-x64\resources\app.asar
    at createError (electron/js2c/asar.js:126:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:545:27)
    at getManifestFromPath (electron/js2c/browser_init.js:4010:26)
    at Function.BrowserWindow.addExtension (electron/js2c/browser_init.js:4432:22)
    at Function.BrowserWindow.addDevToolsExtension (electron/js2c/browser_init.js:4464:40)
    at App.<anonymous> (electron/js2c/browser_init.js:4493:23)
    at Object.onceWrapper (events.js:291:20)
    at App.emit (events.js:208:15)

~~~~


system info
~~~~System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 4.00 GB / 15.87 GB
  Binaries:
    Node: 12.14.1 - E:\Install\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\GoodBoy\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - E:\Install\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 28
      Build Tools: 25.0.1, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
~~~~

**Comment by KishoreBarik** [comment]
Any updates on it? Latest 10.* versions are also not working.

**Comment by RikSchefferOberon** [comment]
yes, 0.9 and 0.11 work for windows

**Comment by KishoreBarik** [comment]
Looks like the issue is with electron v6

[https://github.com/electron/electron/issues/19468](https://github.com/electron/electron/issues/19468)

**Comment by ahmadi-akbar** [comment]
> Looks like the issue is with electron v6. It doesn't open in dark mode. I tried with turning off dark mode it worked.
> 
> [electron/electron#19468](https://github.com/electron/electron/issues/19468)

yes this issue related to electron.
i turned off windows dark mode and finally rn-debugger run correctly. 😊😅

**Comment by rusakovic** [comment]
v0.11.0-beta-2
Windows dark mode. Still not working.
Chrome 80.0.3987.132 (Official Build) (64-bit)

**Comment by zzzloy777** [comment]
react_native_debugger-0.11.3 is running good in dark mode, but not compatible with react 0.61.

To run react_native_debugger-0.10.9 i've changed windows to light mode, and after debugger started, switched back to dark mode and its ok.

**Comment by goxr3plus** [comment]
I am using Version 0.10.10 because expo latest SDK 37 only supports react 0.61 , and i don't know how to open react-native-debugger .

Do you guys found any solution ?

@erik7z

**Comment by afilp** [comment]
I also need to change to "light mode" for the debugger to run.

I have a question:
After we install the EXE, where do you we find it installed to just run it again some other time? (I keep re-installing it). When searching with windows search, I only get the installer:

![image](https://user-images.githubusercontent.com/7850073/83237962-5e774180-a19e-11ea-876d-0ef6c6d39b2b.png)

**Comment by lumotroph** [comment]
> I also need to change to "light mode" for the debugger to run.
> 
> I have a question:
> After we install the EXE, where do you we find it installed to just run it again some other time? (I keep re-installing it). When searching with windows search, I only get the installer:
> 
> ![image](https://user-images.githubusercontent.com/7850073/83237962-5e774180-a19e-11ea-876d-0ef6c6d39b2b.png)

Check your `C:\Users\<user_name>\AppData\Local\react_native_debugger` folder for the `.exe`

**Comment by akanshSirohi** [comment]
Same issue, it is not working with me also on windows 10.
I also try @lumotroph suggested path and found the executable and try to run it but nothing happen...

**Comment by joaovbibiano** [comment]
This is not working on my Windows 10

**Comment by MasterRedStorm** [comment]
Even ligjt mode dosnt work with the current version ( v0.11.5 )

**Comment by MasterRedStorm** [comment]
I cant get it to work on Win 10 :/

**Comment by vadzimk** [comment]
No solution over two years? No need to run it on windows?

**Comment by Blademaster680** [comment]
I just ran into this issue on my new laptop, which I thought was strange seeing it works fine on my Desktop with the same windows settings. What I have found to work for me was to change your Windows 10 Theme settings to the Light mode. For some reason when Windows Colour theme is in Dark mode that is what prevents it from opening. I am not sure why, but hopefully this solution works for others too.

Start > Settings > Personalization > Colors > Change your color to Light instead of Dark

**Comment by shadab-Espranza** [comment]
@Blademaster680  worked for me thanks

**Comment by JaskaranSingh4704** [comment]
> I also need to change to "light mode" for the debugger to run.
> 
> I have a question:
> After we install the EXE, where do you we find it installed to just run it again some other time? (I keep re-installing it). When searching with windows search, I only get the installer:
> 
> ![image](https://user-images.githubusercontent.com/7850073/83237962-5e774180-a19e-11ea-876d-0ef6c6d39b2b.png)

Check your `C:\Users\<user_name>\AppData\Local\react_native_debugger` folder for the `.exe`

**Comment by JaskaranSingh4704** [comment]
> > I also need to change to "light mode" for the debugger to run.
> > I have a question:
> > After we install the EXE, where do you we find it installed to just run it again some other time? (I keep re-installing it). When searching with windows search, I only get the installer:
> > ![image](https://user-images.githubusercontent.com/7850073/83237962-5e774180-a19e-11ea-876d-0ef6c6d39b2b.png)
> 
> Check your `C:\Users\<user_name>\AppData\Local\react_native_debugger` folder for the `.exe`

Thanks this works for me
