### ISSUE TITLE
Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by friederbluemle** [jhen0409/react-native-debugger#668]
React Native Debugger app version: 0.12.1
React Native version: 0.66.4
Platform: Android + iOS
Is real device of platform: Android real device, iOS simulator
Operating System: macOS

Steps to reproduce:

1. Create new React Native project `npx react-native init rnapp`
2. Start React Native Debugger
3. Enable debugging in app
4. Observe crash

```
Uncaught Error: Cannot add node "1" because a node with that id is already in the Store.

The error was thrown at /path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:140545
at c.emit (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:89515)
at /path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:90986
at /path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:347787
at Array.forEach (<anonymous>)
at S.Gc.e.onmessage (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:48:347771)
at S.n (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:3009)
at S.emit (events.js:315:20)
at e.exports.P (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:9318)
at e.exports.emit (events.js:315:20)
at e.exports.dataMessage (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:15409)
at e.exports.getData (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:14651)
at e.exports.startLoop (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:12066)
at e.exports._write (/path/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:8:11421)
at doWrite (_stream_writable.js:403:12)
at writeOrBuffer (_stream_writable.js:387:5)
```

Related issue in https://github.com/facebook/react/: https://github.com/facebook/react/issues/22963

**Comment by TamaraMalakhova** [comment]
The same problem

**Comment by champagneht** [comment]
The same problem

**Comment by champagneht** [comment]
![P)D)BF@Y80E9NCFY_C 7Y`5](https://user-images.githubusercontent.com/32770969/147736726-abc0f4c8-3a2c-4242-9a43-a5ca44968efb.png)

**Comment by champagneht** [comment]
![P)D)BF@Y80E9NCFY_C 7Y`5](https://user-images.githubusercontent.com/32770969/147736779-d29efbac-8d71-4643-a5cc-3c67539ae0d3.png)
The same problem

**Comment by nanxiaobei** [comment]
Same issue. version `v0.12.1`.

**Comment by anhquan291** [comment]
Facing same error. Any updates please?

**Comment by Slyness98** [comment]
In the react-devtools package, I got this all to work by upgrading both react-devtools and react-devtools-core to v4.22.1. If this repo could bump both versions up to put these packages back in sync that should hopefully solve the problem. Until then, I don't think there's a way to use this tool. I have the same error every time I launch, forcing me to go back to just plain react-devtools / browser-based react native debugger which launches with expo. It's a real shame; I love how all of that is integrated in one place with RN-debugger.

For now, I just upgraded react-devtools from npm and customized the port it listens to via react-devtools-core, as documented [here](https://github.com/facebook/react/tree/main/packages/react-devtools-core#react-devtools-core-1). Component and Profiler tabs, plus some console.logs is better than nothing I suppose!

**Comment by AdhamMoussa** [comment]
same issue v0.12.1

**Comment by riskexwandersonandrade** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/86786321/151933719-866a0dc2-0a16-4c00-8bfe-e683b302eda3.png">

**Comment by Alaaa-Drebate** [comment]
same issue here too

**Comment by dkang23** [comment]
same issue

**Comment by dkang23** [comment]
> In the react-devtools package, I got this all to work by upgrading both react-devtools and react-devtools-core to v4.22.1. If this repo could bump both versions up to put these packages back in sync that should hopefully solve the problem. Until then, I don't think there's a way to use this tool. I have the same error every time I launch, forcing me to go back to just plain react-devtools / browser-based react native debugger which launches with expo. It's a real shame; I love how all of that is integrated in one place with RN-debugger.
> 
> For now, I just upgraded react-devtools from npm and customized the port it listens to via react-devtools-core, as documented [here](https://github.com/facebook/react/tree/main/packages/react-devtools-core#react-devtools-core-1). Component and Profiler tabs, plus some console.logs is better than nothing I suppose!

I "npm install"ed 'react-devtools' and 'react-devtools-core' and set them to the same version

   "react-devtools": "~4.14.0",
   "react-devtools-core": "~4.14.0",
and re-installed everything by deleting package-lock.json and node_modules

then ran npm install and it worked

**I think the problem was those packages not being the same version**

**Comment by nancologist** [comment]
On Mac I could not even install react-devtools globally, because of electron. But it finally worked with following options:

`sudo npm i -g react-devtools --unsafe-perm=true --allow-root=true`
 
so as a work-around you can run `react-devtools` in Terminal and connect it to your virtual device

**Comment by farukomer58** [comment]
Installing "'react-devtools" and "react-devtools-core" globally solved this issue by me.
so just running:
1. npm install -g react-devtools
2. npm install -g react-devtools-core

**Comment by Alex1899** [comment]
same issue

**Comment by JavaScriptErika** [comment]
Facing the same issue too

**Comment by DreamEmulator** [comment]
+1

**Comment by igardenaua** [comment]
Same issue on:
- Windows 10
- ReactNative `0.68.0`.

# Problem
The problem occurs due to `react-devtools-core` version mismatch.
React Native debugger uses `"react-devtools-core": "4.14.0"` (as of [v0.12.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.12.0) changelog) but `npx react-native init` comes with the `@latest` version.

# Remarks
When starting a project with `npx react-native init`, it comes with `react-devtools-core` installed, not `react-devtools`. Identify this with `npm list` foreach of these packages (locally in your project, **NOT** global):

![Screenshot_3](https://user-images.githubusercontent.com/32724774/161945741-c40c810a-2d9c-4bc2-ad6a-1aa5a5de735a.png)

So when it comes to `react-devtools-core` dependency, notice that it is a nested dependency of `react-native`, not direct dependency of the root package.

As stated in [https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides), you are able to select different version for **dependencies of your dependencies** with the `override` key in `package.json`. So the first thing that came in my mind, was adding the package version as `override` to `package.json` and running a clean `npm install`:

```json
"overrides": {
    "react-devtools-core": "4.14.0"
}
```
...but **WAIT**! `react-devtools-core` is a dependency of `react-native` not of your package, as mentioned above.

# Solution
1. Run  `npx react-native init YourProjectName`
2. Delete `node_modules` directory (and `package-lock.json` file if any).
3. Add these lines to your `package.json`.
Exact version depends on the react native debugger current `react-devtools-core` version.
Notice that `react-devtools-core` is added as a dependency of `react-native`.
```json
"overrides": {
    "react-native": {
        "react-devtools-core": "4.14.0"
    }
}
```
4. Run `npm install`
5. Uninstall any previous installs of your app, from you device or emulator
6. Now open [React Native Debugger](https://github.com/jhen0409/react-native-debugger)
7. Run `npm run android`
8. Selecting `Debug` from the developer menu, should now debug your app in ReactNativeDebugger

![Screenshot_2](https://user-images.githubusercontent.com/32724774/161948354-c7a5eaa7-9517-470c-a3dc-1181c41501b9.png)

**IMPORTANT NOTE**: Not tested in iOS.

**Comment by ThomasStubbe** [comment]
Or in case you use yarn: 

```
  "resolutions": {
    "react-devtools-core": "4.14.0"
  },
```

**Comment by dudeinthemirror** [comment]
on Mac OS (M1) the following fixed it for me:

```
yarn global add react-devtools react-devtools-core
```

and, in the app's `package.json`:
```
"resolutions": {
    "react-devtools-core": "4.14.0"
  },
```

**Comment by pavelgronsky** [comment]
Hey everyone!!!

[This is my solution](https://gist.github.com/bvaughn/4bc90775530873fdf8e7ade4a039e579?permalink_comment_id=4163357#gistcomment-4163357)

**Comment by samvoults** [comment]
"overrides" only works on npm version 8.3.0 and above. To update npm, run : npm install -g npm

**Comment by rossjackson** [comment]
For those that don't want to use yarn https://github.com/jhen0409/react-native-debugger/issues/620#issuecomment-1022393221

**Comment by Lunotte** [comment]
With React Native Debugger version 0.13.0 and a React Native project in 0.69.4, there is no need to add "overrides" or "resolution" for react-devtools-core in the package.json
