### ISSUE TITLE
ENOENT: no such file or directory, open  RNDebuggerWorker.js

### ISSUE THREAD

**Issue by ksielyov** [jhen0409/react-native-debugger#669]
Error: ENOENT: no such file or directory, open 'file:///Applications/React%20Native%20Debugger.app/Contents/Resources/app.asar/js/RNDebuggerWorker.js'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at getCodeFrame (/Users/mikhailkiselyov/WebstormProjects/languagenow2clone/node_modules/metro/src/Server.js:995:18)
    at /Users/mikhailkiselyov/WebstormProjects/languagenow2clone/node_modules/metro/src/Server.js:1054:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mikhailkiselyov/WebstormProjects/languagenow2clone/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/mikhailkiselyov/WebstormProjects/languagenow2clone/node_modules/metro/src/Server.js:119:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

React Native Debugger app version: [0.11]
React Native version: [0.63.3]
Platform: [IOS and Android.]
Is real device of platform: [No]
Operating System: [macOS - Apple Silicon]

**Comment by kvlknctk** [comment]
same issue

**Comment by s0rta** [comment]
trying to open the file in the browser confirms that it does not exist, at least not at that path.

**Comment by FrogBattle** [comment]
Same here.
Versions:
- Expo 45 SDK
- React Native: ```0.68.2```
- React: ```17.0.2```
- Yarn resolution:
```   "resolutions": {
    "react-devtools-core": "4.14.0"
  },
```
- React Native Debugger App: ```0.12.1```

Environment:
- Expo Managed project
- iOS Simulator
- MacOS Monterey

The issue occurred after upgrading to newer Expo, React/React Native versions.

**Comment by anujraghuvanshi** [comment]
Getting the same issue React native (CLI). Not able to connect to debuggger

**Comment by jobayer977** [comment]
Same issues I'm facing

**Comment by KAMRONBEK** [comment]
Any updates on this issue?

**Comment by alexzobi** [comment]
Just FYI I found myself here because I had just upgraded to RN0.70.6. What I didn't think about was that the upgrade uses Hermes as a default. RNDebugger requires the use of the V8 engine to run, which obviously means Hermes breaks RNDebugger. If you're here for the same reason, here are two solutions: 

1. you can disable hermes (and all the benefits that come along with it)
2. you can use a different debugging tool. There has been a [feature request](https://github.com/jhen0409/react-native-debugger/issues/573) for Hermes support, but I'm not sure the owner has the overhead for this. 

If you choose to stick with Hermes, in order to clear the above on ios, you'll need to clear your device settings. Device -> Erase all content and settings.

**Comment by SliverYuki** [comment]
same issue, any update?

**Comment by coldSeattle** [comment]
same issue +

**Comment by tlhai-cmc** [comment]
same issue +
