### ISSUE TITLE
devtools does not show. it's blank

### ISSUE THREAD

**Issue by pouriabagheri** [jhen0409/react-native-debugger#789]
React Native Debugger app version: 0.14.0
React Native version: 0.72
Platform: iOS, Android
Is real device of platform: Both
Operating System: macOS

the dev-tool is blank and not showing anything
the console throws this error on first run
```
bundle.js:2 TypeError: Cannot read properties of undefined (reading 'action')
    at r.value (bundle.js:6:262610)
    at r.value (bundle.js:6:262058)
    at xu (bundle.js:2:939665)
    at wu (bundle.js:2:939440)
    at bu (bundle.js:2:938978)
    at bundle.js:2:950762
    at Sl (bundle.js:2:951273)
    at ll (bundle.js:2:945029)
    at $o (bundle.js:2:885729)
    at bundle.js:2:951268
    at Sl (bundle.js:2:951273)
    at il (bundle.js:2:943770)
    at S (bundle.js:2:991848)
    at Immediate.D (bundle.js:2:992380)
    at process.processImmediate (node:internal/timers:476:21)

bundle.js:2 TypeError: Cannot read properties of undefined (reading 'action')
    at r.value (bundle.js:6:262610)
    at r.value (bundle.js:6:262058)
    at xu (bundle.js:2:939665)
    at wu (bundle.js:2:939440)
    at bu (bundle.js:2:938978)
    at bundle.js:2:950762
    at Sl (bundle.js:2:951273)
    at ll (bundle.js:2:945029)
    at $o (bundle.js:2:885729)
    at bundle.js:2:951268
    at Sl (bundle.js:2:951273)
    at il (bundle.js:2:943770)
    at S (bundle.js:2:991848)
    at Immediate.D (bundle.js:2:992380)
    at process.processImmediate (node:internal/timers:476:21)
```

<img width="1440" alt="Screenshot 2023-09-06 at 9 39 53 AM" src="https://github.com/jhen0409/react-native-debugger/assets/5735478/ba532b69-5e84-4731-9c9e-c2f5e72e4b4f">

I have tried:
reinstalling the debugger
removing all other debugging tools from chrome
clearing app and yarn cache
toggle DevTools react
toggle DevTools redux

Does anyone know what are the files affected by the debugger so i can delete them manually and do a clean install ?

**Comment by pouriabagheri** [comment]
so I managed to fix it by clean installing the react native debugger

1. brew uninstall --cask react-native-debugger
2. rm -rf  ~/Library/Application Support/React Native Debugger
3. brew install --cask  react-native-debugger

**Comment by suleymanbasbug** [comment]
> so I managed to fix it by clean installing the react native debugger
> 
> 1. brew uninstall --cask react-native-debugger
> 2. rm -rf  ~/Library/Application Support/React Native Debugger
> 3. brew install --cask  react-native-debugger

Its not worked for me

**Comment by MarkPan726** [comment]
I have a similar question the react devtools is blank and can't toggle, I resolve it by installing react-devtools:
`yarn global add react-devtools@^4.22.0`.

**Comment by fomichova** [comment]
Has anyone fixed this issue? I have the same. Nothing of solutions does not work.

**Comment by jamesfg** [comment]
> > so I managed to fix it by clean installing the react native debugger
> > 
> > 1. brew uninstall --cask react-native-debugger
> > 2. rm -rf  ~/Library/Application Support/React Native Debugger
> > 3. brew install --cask  react-native-debugger
> 
> Its not worked for me

I did this but command 2 did not work for me so I manually deleted the folder and reinstalled and it worked.

**Comment by sayurimizuguchi** [comment]
I fixed this issue. However, I could not solve this by uninstalling and installing it again. Then I remembered we have cache files for every application. With that in mind, the steps I followed to fix (Mac OS):

1. Open Finder
2. In the top, select `Go` -> `Go to Folder` ->` /Users/${yourUser}/Library/Caches/`
3. Go to `Application Support` folder -> Then delete the entire folder called `React Native Debugger`
4. Open the application again; it should be working.


![Screen Shot 2023-11-28 at 1 27 21 PM](https://github.com/jhen0409/react-native-debugger/assets/23122214/df31b9ba-7bcf-404e-8faa-61a5d274d2f5)

**Comment by meantgx** [comment]
> I fixed this issue. However, I could not solve this by uninstalling and installing it again. Then I remembered we have cache files for every application. With that in mind, the steps I followed to fix (Mac OS):
> 
> 1. Open Finder
> 2. In the top, select `Go` -> `Go to Folder` ->` /Users/${yourUser}/Library/Caches/`
> 3. Go to `Application Support` folder -> Then delete the entire folder called `React Native Debugger`
> 4. Open the application again; it should be working.
> 
> ![Screen Shot 2023-11-28 at 1 27 21 PM](https://private-user-images.githubusercontent.com/23122214/286362412-df31b9ba-7bcf-404e-8faa-61a5d274d2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Mjk3NTAsIm5iZiI6MTcwMjYyOTQ1MCwicGF0aCI6Ii8yMzEyMjIxNC8yODYzNjI0MTItZGYzMWI5YmEtN2JjZi00MDRlLThmYWEtNjFhNWQyNzRkMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4MzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0Y2UxOWEyMTZlZGI2ZTdlNTA5NjIzNTczZWY1Y2ZiMWQzMzI0YjE4MDNmNTkwNWU3MzBmNTg4NWVmNTUwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5fbrdSzUAi80bLWMFlhLql_CqRPCb3xy_ZuxT94Fj14)

It works. Great ! 💯

**Comment by fdrcslv** [comment]
Having the same problem, installing it with dpkg. Removing and reinstalling does not work. I tried installing react-devtools:
`yarn global add react-devtools@^4.22.0 `

**Comment by mukeshmaurya2002** [comment]
> I fixed this issue. However, I could not solve this by uninstalling and installing it again. Then I remembered we have cache files for every application. With that in mind, the steps I followed to fix (Mac OS):
> 
> 1. Open Finder
> 2. In the top, select `Go` -> `Go to Folder` ->` /Users/${yourUser}/Library/Caches/`
> 3. Go to `Application Support` folder -> Then delete the entire folder called `React Native Debugger`
> 4. Open the application again; it should be working.
> 
> ![Screen Shot 2023-11-28 at 1 27 21 PM](https://private-user-images.githubusercontent.com/23122214/286362412-df31b9ba-7bcf-404e-8faa-61a5d274d2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjIxMTEsIm5iZiI6MTcxMzk2MTgxMSwicGF0aCI6Ii8yMzEyMjIxNC8yODYzNjI0MTItZGYzMWI5YmEtN2JjZi00MDRlLThmYWEtNjFhNWQyNzRkMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEyMzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjJjZjgzODgzOTM5OGQ1M2UxOTg3NGIyYmJkZDgxM2ViZTAyOTA5YWU2NTYzZTc1YjhmMTViYTc0MmRhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GuOfsYLmZXiZ71iMON_yBavuDX--Q40yif4Gjm6rk9Y)

thanks it working

**Comment by VladKNT** [comment]
> I fixed this issue. However, I could not solve this by uninstalling and installing it again. Then I remembered we have cache files for every application. With that in mind, the steps I followed to fix (Mac OS):
> 
> 1. Open Finder
> 2. In the top, select `Go` -> `Go to Folder` ->` /Users/${yourUser}/Library/Caches/`
> 3. Go to `Application Support` folder -> Then delete the entire folder called `React Native Debugger`
> 4. Open the application again; it should be working.
> 
> ![Screen Shot 2023-11-28 at 1 27 21 PM](https://private-user-images.githubusercontent.com/23122214/286362412-df31b9ba-7bcf-404e-8faa-61a5d274d2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDIzNDAsIm5iZiI6MTcxODMwMjA0MCwicGF0aCI6Ii8yMzEyMjIxNC8yODYzNjI0MTItZGYzMWI5YmEtN2JjZi00MDRlLThmYWEtNjFhNWQyNzRkMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE4MDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMjU2MGVhN2Q4YWRjMDhhNGEzODVjM2EzMTM3ZDM2NTExMTBiYzY4NzJiN2U4N2M0NGM1YTI2MzNkYTkyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IU1_itwx9XP4qS7DFE-FhhaIu8z0h_1m9QWC8Fz2Eog)

I did not find the "React Native Debugger" folder under this path "/Users/${yourUser}/Library/Caches/Application Support/", but managed to solve this problem by turning off "Cache Storage" in the "Application" tab of the debugger.
The react-native-debugger version that I used is [0.14.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.14.0).

<img width="951" alt="Screenshot 2024-06-13 at 21 05 32" src="https://github.com/jhen0409/react-native-debugger/assets/18424547/70fe38bf-db63-4280-8060-d9c0b2f7d0ce">

**Comment by lmff85** [comment]
Don't know if this will help anyone but when my redux tools disappeared and I couldn't find the debugger preferences in the aforementioned path `/Users/<user>/Library/Caches/Application Support/React Native Debugger`, I eventually found the folder in question at `/Users/Library/ApplicationSupport/React Native Debugger`. 

Removing it and restarting the debugger brought redux tools back.

**Comment by powext** [comment]
I can't find the caches in both 
/Users/<user>/Library/Caches/Application Support/React Native Debugger
and 
/Users/Library/ApplicationSupport/React Native Debugger
Either toggling the cache storage switch in in the image above.
Also reinstalling is not working.

**Comment by powext** [comment]
It worked removing `/Users/{user}/Library/Application\ Support/React\ Native\ Debugger`

**Comment by palTarun** [comment]
> npm i react-devtools@^4.22.0

Worked for me
